### ISSUE TITLE
Order of hints is significant

### ISSUE THREAD

**Issue by matijapretnar** [Andromedans/andromeda#119]
The proof below goes through:
```
Parameter Bool : Type.
Parameter T : Bool.
Parameter F : Bool.

Parameter ind_Bool :
  ∀ [P : Bool → Type] P T → P F → ∀ [b : Bool] P b.

Parameter ind_Bool_T :
  ∀ [P : Bool → Type] [t : P T] [f : P F]
    ind_Bool P t f T ≡ t.
Parameter ind_Bool_F :
  ∀ [P : Bool → Type] [t : P T] [f : P F]
    ind_Bool P t f F ≡ f.

Parameter And : Bool → Bool → Bool.
Parameter And_def :
  ∀ [b1 b2 : Bool] And b1 b2 ≡ ind_Bool (λ [_] Bool) b1 F b2.

Let And_b_T : forall [b : Bool] And b T == b :=
  λ [b] beta ind_Bool_T; And_def in refl b.

Let And_b_F : forall [b : Bool] And b F == F :=
  λ [b] beta ind_Bool_F; And_def in refl F.

Beta And_def.
Beta And_b_T.
Beta And_b_F.

Let And_n_Z : forall [b : Bool] And T b == b :=
  ind_Bool (λ [b] And T b == b)
    (refl T)
    (refl F).
```
However, if I change the hints to
```
Beta And_b_T.
Beta And_b_F.
Beta And_def.
```
it fails with
```
line 31, characters 5-12: Typing error
  failed to check that the term T is equal to And T T
```
It works if I write `Hint And_def.` instead of `Beta And_def.` or even if I remove the line.

**Comment by SkySkimmer** [comment]
The order of beta hints will be significant any time the resulting rewrite system is not confluent.

eg here we have `And T T --> T` by `And_b_T` and `And T T --> (λ [_] Bool) T F T` by `And_def`, to get confluence we would need to add `ind_Bool_T` (and `ind_Bool_F` for the other case).

**Comment by matijapretnar** [comment]
Yes, I imagine hints will be tried in different order. But the equation should still be provable under the given hints: if one of them applies but the further proof fails, we should try the next one in order.

**Comment by andrejbauer** [comment]
I disagree. The beta hints are there to give you a rewrite system and they should not backtack as that is a sure way to cycle. The hints are tried in the reverse order of installation. In general, when you have something like a definition of `and` in terms of `ind` you would *not* install the definition itself as a beta hint because you almost never want to get the definition unfolded. Just install the other ones instead.

**Comment by matijapretnar** [comment]
Thanks! I was already doing that (not installing `And_def`) but I was wondering why things don't work as expected. My mistake was in thinking that beta hints backtrack. Your explanation makes sense.
