### ISSUE TITLE
Simplification in error messages

### ISSUE THREAD

**Issue by matijapretnar** [Andromedans/andromeda#120]
I am wondering why terms in error messages are not simplified. For example, I get
```
File "primes.m31", line 183, characters 5-39: Typing error
  this expression should have type
  {witness : N,
   proof : (λ [k : N] times k (S m₉₆₆) ≡ fact (S (S n₉₉₈)))
             witness}
  but has type
  (λ [n0 : N]
     (λ [m0 : N] [n1 : N]
        (λ [A : Type] [P : A → Type] {witness : A, proof : P witness}) N
          (λ [k : N] times k m0 ≡ n1)) (S m₉₆₆) (fact (S n0)))
    n₉₉₈
```
but the following is much easier to understand:
```
File "primes.m31", line 183, characters 5-39: Typing error
  this expression should have type
  {witness : N,
   proof : times witness (S m₉₆₆) ≡ fact (S (S n₉₉₈))}
  but has type
  {witness : N,
   proof : times witness (S m₉₆₆) ≡ fact (S n₉₉₈)}
```
I understand you can't get a WHNF, but one would at least expect beta-reductions for variables that appear at most once.

**Comment by andrejbauer** [comment]
The way to do this is to call `Simplify` on the terms first.

**Comment by SkySkimmer** [comment]
`Simplify` has been retired.
At some point we will probably want a smart error printing which simplifies terms if that doesn't make the error incomprehensible.

**Comment by andrejbauer** [comment]
Closed as there is no more `simplify`.
