### ISSUE TITLE
Smarter structure type checking

### ISSUE THREAD

**Issue by SkySkimmer** [Andromedans/andromeda#124]
Consider the evaluation of `{ x := cx, y := cy }` (assuming no bound variables in the environment):
- we evaluate `cx => |- ex : tx`
- we add a fresh `x : tx` and `eqx : x == ex`, and install `eqx` as a beta hint
- we evaluate `cy => x : tx, eqx : x == ex |- ey : ty`
- now since we track used assumptions, we now whether `ty : Type` needs `eqx`. If it does we can instantiate `x := ex` and `eqx := refl ex` in it to get `|- { x := ex, y := ey } : { x : tx, y : ty[ex/x][refl ex/eqx] }`. Otherwise we get `|- { x := ex, y := ey } : { x : tx, y : ty }` which may be a dependent sum (exactly when `ty` depends on `x`).

This isn't implemented since tracking assumptions is new, but it should be.

**Comment by andrejbauer** [comment]
Why do you want to instantiate `x` with `ex` and `eqx` with `refl ex`? If a dependency was detected, it should be kept there.

**Comment by SkySkimmer** [comment]
It would be a dependency in the resulting signature. So eg

    A : Type
    P : A -> Type
    Q : forall x : A, P x -> Type
    f : forall [x : A] [y : P x] Q x y
    a : A
    b : P a
    { x := a, y := f x b } : { x : A, y : Q x b }
The type `{x : A, y : Q x b}` is valid only if we can derive `forall [x : A] P x == P a`, which we can't.
So instead we derive `{ x := a, y := f x b } : { x : A, y : Q a b }` or `{x := a, y := f a b } : { x : A, y : Q a b }` (not sure if there's a significant difference).

**Comment by andrejbauer** [comment]
Oh, I see. Yes, we talked about this before.

**Comment by andrejbauer** [comment]
Obsolete since signatures are named.
