### ISSUE TITLE
Should we whnf in where clauses

### ISSUE THREAD

**Issue by andrejbauer** [Andromedans/andromeda#130]
In `c1 where c2 := c3` we compute the whnf of (the value of) `c2` to see which atom it is, say atom `x`. In case there is a beta hint that rewrites `x` this could be quite surprising, and maybe we should avoid the normalization (the normalization happens because of a call to `Equal.as_atom`).

**Comment by SkySkimmer** [comment]
We don't have whnf any more. While we could have an as_atom operation I don't think that would be useful, so I'm closing this.
