### ISSUE TITLE
Possible non reducing spines that should reduce

### ISSUE THREAD

**Issue by SkySkimmer** [Andromedans/andromeda#132]
Consider a term

      (lambda [x : A] [y : B] : C. t) @[x : A, y : B' :> C'] [e1, e2]

such that `Pi [y : B] C == Pi [y : B'] C'`
The term is supposed to be an abbreviation for

    ((lambda [x : A] : (Pi [y:B] C). lambda [y : B] : C. t) @[x : A :> Pi [y : B'] C'] e1) @[y : B'[e1/x] :> C'[e1/x]] e2
but since we compare the whole annotations on possible beta redexes only the second reduces (to `(lambda [y : B[e1/x]] : C[e1/x]. t[e1/x]) @[y : B'[e1/x] :> C'[e1/x]] e2`
It may be possible to work around this by deriving that the first term is equal to the second, then deriving that the second is equal to the reduced form.

**Comment by andrejbauer** [comment]
Is this still an issue now that the spines are gone?

**Comment by andrejbauer** [comment]
Oops, did not mean to close.

**Comment by SkySkimmer** [comment]
It isn't.
