### ISSUE TITLE
Eta rules

### ISSUE THREAD

**Issue by SkySkimmer** [Andromedans/andromeda#134]
The following equalities are not derivable any more:

    f == lambda x, f x

    s == { x = s.x, y = s.y, ... }

Notably this means we lose `forall x y : {}, x == y`.
For functions we can easily have a constant for function extensionality if we care to, so the impact is small.
However for structures we would need a new assumption for every ordering of labels (we need to assume `forall A, forall B : A -> Type, forall a b : {x : A, y : B x}, a.x == b.x -> a.y == b.y -> a==b` and `forall A, forall B : A -> Type, forall a b : {y : A, x : B x}, a.y == b.y -> a.x == b.x -> a==b` separately, and so on for every set of labels). That seems quite inconvenient.

It seems then that we should have some `by_eta e1 e2` construct (similar to `congruence`) which allows to derive both of the previous structure eta rules.
Should it also derive the eta rule for functions?

**Comment by andrejbauer** [comment]
Agreed about structures. And since user can assume function extensionality we shouldn't worry about eta. By the way, the eta rule for equality type `forall (A : Type) (a b : A) (p q : a == b), p == q` is assumed in a number of places, so what do we do about that?

**Comment by SkySkimmer** [comment]
When is it assumed?

**Comment by andrejbauer** [comment]
I would worry about every instance where we use `refl` in the kernel.

**Comment by andrejbauer** [comment]
Hmm, no actually that is not a worry. Here's the thing. Without the eta rule for equality types I do not see how to derive the J eliminator for equality types, and that *is* worrisome. Last summer @vladimirias, @haselwarter and I wondered about this for a while: if you have *only* equality reflection for equality type, does something go wrong?

**Comment by SkySkimmer** [comment]
If we have the J eliminator then we have the eta rule, see eg https://ncatlab.org/nlab/show/extensional+type+theory

**Comment by andrejbauer** [comment]
The `J` eliminator is a pain in the neck to implement, we had it. It's better to provide built-in eta rule for equality. We need something like `reduce` for eta rules, for instance `decompose`. It would apply the relevant eta rule.
