### ISSUE TITLE
State

### ISSUE THREAD

**Issue by SkySkimmer** [Andromedans/andromeda#136]
We're going to need some form of state, see #135

**Comment by andrejbauer** [comment]
@haselwarter will not be happy with real state. We have two options: to track all state and make him happy, or to worry about it later. I am inclined to first not worry but to make sure that all state is encapsulated in a module with an abstrac interface, so it should be easy to fix it later. Does that sound like a plan?

**Comment by haselwarter** [comment]
Sounds okay to me. My guess is that we can keep the implementation pure;
i don't expect this to be a bottleneck.

What about the state that we currently carry around in the environment?

**Comment by andrejbauer** [comment]
The environment is explicitly passed around so it is not "real state" (in the sense of OCaml `mutable` or `ref`).

**Comment by SkySkimmer** [comment]
#144 has pure state.
