### ISSUE TITLE
Better shadowing

### ISSUE THREAD

**Issue by SkySkimmer** [Andromedans/andromeda#137]
If we do something like

    let x = foo
    constant x : bar

there is no way to refer to the constant `x` because top level declarations are always shadowed by bound variables.
This is silly.

**Comment by andrejbauer** [comment]
What would not be silly? Many languages just forbit all shadowing, but I suspect that'll be annoying. Pick an option:

1. No shadowing *at top level*.
2. Constants shadow bound names.
3. No shadowing anyhwere.

**Comment by christopherastone** [comment]
I would think the silly bit is that the constant is defined second, but gets shadowed by the variable.

**Comment by andrejbauer** [comment]
All three options fix that problem, which one strikes you as most reasonable?

**Comment by christopherastone** [comment]
1, 4, or 5. 
4. Treat variables and constants the same w.r.t. shadowing (second always wins)
5. Constants and variables are written differently (e.g., capital va. lowercase) and can't shadow.

Of course 1 has problems in an interactive context.

**Comment by andrejbauer** [comment]
I could go with 4 as it is the most uniform solution.

**Comment by haselwarter** [comment]
4, possibly 1

**Comment by andrejbauer** [comment]
Actually, we cannot do 4 because we look up constants by name during evaluation. Thus, if we declare the same constant twice there will be confusion. I am going to implement 1. Shadowing will still be permitted locally.

**Comment by SkySkimmer** [comment]
We don't we do 4 while refusing multiple declarations for a constant name?
When we declare a constant A : T, we
-insert const A : T in the (dynamic) environment, which is forbidden if there already is a declaration for const A
-bind the name A to (|- const A : T) in the lexical environment
Same thing with operations and data constructors.
Arities/typing make it more complicated and annoying but should still be feasible.

In any case, I use top level shadowing + #include to get around the lack of state so I don't want to see it go yet.
