### ISSUE TITLE
Fatal error: exception Not_found

### ISSUE THREAD

**Issue by SkySkimmer** [Andromedans/andromeda#139]
Happens on https://github.com/SkySkimmer/andromeda/blob/equal-tac/tests/beta-sigma.m31
It appears that at some point we lose the context: a debug print (with --dependencies) indicates that we try to whnf

    (⊢ (λ (y : B ((a)^{{x₂₈₃,  y₂₈₄ ; }})),
              (a)^{{x₂₈₃,  y₂₈₄ ; }})^{{x₂₈₃, y₂₈₄ ; }}
         : Π (b : B a), (λ (_ : sigT A B), A) (existT A B a ((b)^{{ ; b}})))
As you can see `x283` and `y284` are proof irrelevant dependencies yet the context is empty.

**Comment by andrejbauer** [comment]
Probably my fault, will look into it.

**Comment by SkySkimmer** [comment]
@haselwarter and I looked at it, it's probably a problem with the Equal.Monad.abstract_hyps function (meaning my fault ;))
