### ISSUE TITLE
Feature request: Debug mode

### ISSUE THREAD

**Issue by JasonGross** [Andromedans/andromeda#18]
It would be nice to be able to ask brazilians to ship back a transcript of their hint usage: for each goal that needs rewriting hints, a list of the hints used, and the final things that it had to unify.  Something between `-V 2` and `-V 3`.  I'm ok with this being a whole-file or command line option, but it would be nicer to have an `equation_debug` and `rewrite_debug` and a `Set Debug Hints.` or something.

**Comment by andrejbauer** [comment]
I am closing this because there are no more hints in the kernel. They are user defined. We can open a separate issue for "better debugging" (but we probably want "better error messages" first).
