### ISSUE TITLE
Improve structures

### ISSUE THREAD

**Issue by SkySkimmer** [Andromedans/andromeda#189]
The following are still necessary:
- generic matching of signatures, structures and projections (especially projections, we can't do whnf without it). Matching signatures would also let us do a sane `as_signature`.
- generic construction of structures and projections for a known signature (mostly useful for snf, can already be faked by registering custom functions eg `build_foo : forall x : bar, foo` and `project_x : forall s : foo, bar` when `foo = { x : bar }`)
- parametric signatures
- eta rule

Anything else?

**Comment by andrejbauer** [comment]
Do you have a suggestion what the pattern matching would look like for these?

**Comment by andrejbauer** [comment]
Perhaps for generic matching of signatures: `?x .?l` where `.` and `?` must have no space? For a structure and a signature maybe `?s:structure` and `?s:signature`?

**Comment by SkySkimmer** [comment]
>Perhaps for generic matching of signatures: ?x .?l where . and ? must have no space?
Do you mean for projections? What would `l` be bound to?
In general we should think about what the result of a successful match should be before trying to figure out the syntax.

**Comment by andrejbauer** [comment]
`l` would bind to a string. We also need generic notation to go in the other direction.

**Comment by andrejbauer** [comment]
Partially dealt with in #190.

**Comment by SkySkimmer** [comment]
Only #199 remains.
