### ISSUE TITLE
Access to assumptions

### ISSUE THREAD

**Issue by andrejbauer** [Andromedans/andromeda#193]
Given a judgment `Γ |- e : A` we can use pattern matching to get to `e` and `A` but there is no way of accessing `Γ`.  Here is a proposal that @SkySkimmer does not like: `assumptions c` gives the list of assumptions of the judgement that `c` evaluates to. The assumptions are guaranteed to be listed in order of dependency (you first see the non-dependent ones).

**Comment by andrejbauer** [comment]
Another possibility, which is cheaper and faster, is to be able to check wheter a judgement depends on an atom. Or we could generally want to know whether two terms have a disjoint set of assumptions.

**Comment by andrejbauer** [comment]
Without access to the assumptions, how do we compute the universal closure of a judgement? (`x:A, y:B |- e :A` should map to `|- (lambda (x:A) (y:B), e) : forall (x : A) (y : B), T`)

**Comment by haselwarter** [comment]
Implemented by #202
