### ISSUE TITLE
Generic operations

### ISSUE THREAD

**Issue by SkySkimmer** [Andromedans/andromeda#236]
In `std/equal.m31` there is a massive amount of boilerplate to provide `equality_in`. It seems like it could be replaced by
```
let equality_in state = handler
   | _op ?op ?vs => fun state =>
      match (with equality state handle _op op vs) with
        (?v,?state) => yield v state
   | val ?v => v
   | finally ?f => f state
end
```
The top handler would still be boilerplate but it would help.

**Comment by andrejbauer** [comment]
Sorry, what is this about? Permuting state with any operation?

**Comment by SkySkimmer** [comment]
It's about handling operations in a generic way, similar to we can do with structures.
The goal here is to take a state handler and make it return just the end value.

**Comment by andrejbauer** [comment]
I am closing this since I am not keen on hacking handlers like this. The boilerplate code is gone anyway.
