### ISSUE TITLE
Bug in equality

### ISSUE THREAD

**Issue by andrejbauer** [Andromedans/andromeda#239]
Any idea why this fails?

    (* Suppose we have a monoid G *)
    constant G : Type
    constant ( * ) : G → G → G
    constant e : G

    constant unitLeft: ∏ (x : G), e * x ≡ x
    constant unitRight: ∏ (x : G), x * e ≡ x
    constant assoc: ∏ (x y z : G), (x * y) * z ≡ x * (y * z)

    (* A G-set is a set with an action by G *)
    signature GSet = {
      set : Type,
      act : G → set → set,
      actUnit : ∏ (x : set), act e x ≡ x,
      actMul : ∏ (a b : G) (x : set), act (a * b) x ≡ act a (act b x)
    }

    (* A G-morphism is a map between G-sets that commutes with the actions *)
    signature GMor = {
      dom as A : GSet,
      cod as B : GSet,
      fnc as f : A.set → B.set,
      fncMul : ∏ (a : G) (x : A.set), B.act a (f x) ≡ f (A.act a x)
    }

    (* The G-morphisms from A to B *)
    let Hom = fun A B => (GMor using dom = A and cod = B end)

    (* The identity morphism *)
    let id : ∏ (A : GSet), Hom A A =
      λ A, { 
             fnc = (λ x, x),
             fncMul = (λ (a : G) (x : A.set), refl (A.act a x))
           }

    (* Composition of morphisms. Why don't the hints work here? *)
    let comp : ∏ (A B C : GSet), Hom B C -> Hom A B -> Hom A C =
      λ A B C g f,
        { fnc = (λ x, g.fnc (f.fnc x)),
          fncMul = 
             (with local (lbeta g.fncMul) handle
              with local (lbeta f.fncMul) handle
                λ (a : G) (x : A.set), refl (C.act a (g.fnc (f.fnc x))))
        }

**Comment by andrejbauer** [comment]
Btw, changing the definition of `Hom` to

    let Hom = λ (A B : GSet), GMor using dom = A and cod = B end

does not matter much. It is as if somehow equality checking compares arguments of applications before normalizing them.

**Comment by andrejbauer** [comment]
It's a case of the checking mode not propagating through the handlers. With this as the definition of `comp`

    (* Composition of morphisms. Why don't the hints work here? *)
    let comp : ∏ (A B C : GSet), Hom B C -> Hom A B -> Hom A C =
      λ A B C g f,
        { fnc as h = (λ x, g.fnc (f.fnc x)),
          fncMul = 
             (with local (lbeta g.fncMul) handle
              with local (lbeta f.fncMul) handle
                (λ a x, refl (C.act a (g.fnc (f.fnc x)))) :
                ∏ (a : G) (x : A.set), C.act a (h x) ≡ h (A.act a x))
        }

The error message seems a bit more puzzling (it cannot establish equality of two terms that are β-convertible).

**Comment by andrejbauer** [comment]
I understand why it doesn't work, and I think the reason might be this: when we try to figure out whether a β-hint may be applied, we do not whnf the arguments, do we? For instance

    constant A : Type
    constant f : A → A
    constant a : A
    constant eq : f a ≡ a
    do add_beta eq
    do refl a : f a ≡ a
    do refl a : f ((λ (x : A), x) a) ≡ a

The last one fails because it compares `(λ (x : A), x) a` with `a` directly.

**Comment by SkySkimmer** [comment]
You're supposed to set_reducing if you want arguments to be reduced.

**Comment by andrejbauer** [comment]
Is there a local version of `set_reducing`?

**Comment by SkySkimmer** [comment]
It doesn't work with the `local` function but if it's done inside an equality handler the effects are local to it.
So you can do `with fasteq tt handle set_reducing ...; c`

**Comment by andrejbauer** [comment]
Hmm, I need something like `set_reducing C.act [lazy, eager]` which gives `unhandled operation failure`.

**Comment by SkySkimmer** [comment]
Reducing arguments for projections aren't supported yet.

**Comment by haselwarter** [comment]
We used to whnf arguments when trying to apply beta hints.
https://github.com/Andromedans/andromeda/blob/ef13bd3fc1b9ba4d9cca33ddf94e70358c01f399/src/nucleus/equal.ml#L756
https://github.com/Andromedans/andromeda/blob/ef13bd3fc1b9ba4d9cca33ddf94e70358c01f399/src/nucleus/equal.ml#L621

**Comment by haselwarter** [comment]
For the record, the syntax for local `set_reducing` is like this:
```
      fncMul = 
         (with local (lbeta g.fncMul) handle
          with local (lbeta f.fncMul) handle
          let _ = set_reducing C.act [eager,eager] in
```

**Comment by haselwarter** [comment]
The problem with this example though is not with normalisation, but with the fact that handlers are opaque for checking and the hints aren't used. Pushing the equality-check in with an ascription makes the example work:
```
[...]
            λ (a : G) (x : A.set), refl (C.act a (g.fnc (f.fnc x))) :
                                   (C.act a (g.fnc (f.fnc x))) ≡ g.fnc (f.fnc (A.act a x)))
    }
```

**Comment by SkySkimmer** [comment]
Is this still a problem?

**Comment by andrejbauer** [comment]
Closing as we do not have signatures anymore
