### ISSUE TITLE
Signatures revisited

### ISSUE THREAD

**Issue by andrejbauer** [Andromedans/andromeda#242]
I tried to use signatures with sharing to define categories and slice categories. It is painful and I am getting convinced that having *only* sharing is not enough. I might try parameterized signatures, to see how that works.

At the very list we would want dependent sums, which are a form of parameterized signature:

    signature Σ (A : Type) (B : A -> Type) = { fst : A, snd : B fst }.

To see why having only sharing is annoying, try defining Σ..

**Comment by haselwarter** [comment]
Something like the following?
```
signature sigma = {A : Type, B : A → Type, fst : A, snd : B fst}

let Σ = fun A B ⇒ sigma using A = A and B = B and fst and snd end
let Σ' = λ (A : Type) (B : A → Type), sigma using A = A and B = B and fst and snd end

constant S : Type
constant T : S → Type
constant s : S
constant t : T s
do {fst = s, snd = t} : Σ S T
do {fst = s, snd = t} : Σ' S T
```

```
Signature sigma is declared.
Σ is defined.
Σ' is defined.
Constant S is declared.
Constant T is declared.
Constant s is declared.
Constant t is declared.
⊢ {fst = s, snd = t} : sigma using A = S and B = T and fst and snd end
⊢ {fst = s, snd = t}
  : (λ (A : Type) (B : A → Type), sigma using A = A and B = B and fst and
         snd end) S T
```

**Comment by SkySkimmer** [comment]
`and fst and snd` this isn't needed any more.

**Comment by haselwarter** [comment]
Indeed, lovely! Printing still prints it though.

**Comment by SkySkimmer** [comment]
There would need to be an occurs check somewhat like for printing arrows to change that.

**Comment by andrejbauer** [comment]
So if we fix the printing of singatures with sharing, this would actually work. By the way, I'd define

    signature sigma = {base : Type, family : A → Type, fst : A, snd : B fst}
    let Σ = fun A B ⇒ sigma using A = A and B = B and fst and snd end

and then if `p : \Sigma A B` we can write `p.base` and `p.family`. Would that be useful for anything?

**Comment by SkySkimmer** [comment]
Signatures don't exist anymore.
