### ISSUE TITLE
Parallel let rec is broken

### ISSUE THREAD

**Issue by SkySkimmer** [Andromedans/andromeda#244]
See https://github.com/SkySkimmer/andromeda/blob/reducing/tests/multiple-letrec.m31

**Comment by andrejbauer** [comment]
Here's is an example which you can run with `--no-prelude` that shows that the environments get messed up:

    let print = external "print"

    let lies _ = print "IF THIS GETS PRINTED PHILIPP WILL EAT A CHICKEN"

    let rec f x y = print ("f",x,y);
      match (x,y) with
        | (?a::?la,?b::?lb) => f ((g a b), (h la lb))
        | _ => tt
      end

    and g a b = print ("g",a,b);
      a::[b]

    and h la lb = print ("h",la,lb);
      [la, lb]

    data A 0
    data B 0
    data a 0
    data b 0

    do f [A,a] [B,b]

By the way, did you mean to write `f ((g a b), (h la lb))` instead of `f (g a b) (h la lb)`?

**Comment by SkySkimmer** [comment]
I didn't mean to write that.
