### ISSUE TITLE
Make callback handlers checking-transparent

### ISSUE THREAD

**Issue by haselwarter** [Andromedans/andromeda#245]

**Comment by andrejbauer** [comment]
What precisely is this about? I suppose you mean that in some cases we can push checking mode through a handler?

**Comment by SkySkimmer** [comment]
It would be nice if something like the following worked:
```
handle lambda x, op x with
  | op ?v => yield (f v)
end : A -> A
```
However it can't work if the handler is instead
```
handle lambda x, op x with
  | val _ => lambda y, y
  | op ?v => yield (f v)
end : A -> A
```
or even
```
handle lambda x, op x with
  | op ?v => print "HAHA" (* will get coerced ;) *)
end : A -> A
```

Essentially it can only work when the handler has only operation cases which are of the form `op ... => yield c` and `c` doesn't use `yield`, ie defining callbacks for some operations.
This is also something that could be a top handler.

**Comment by andrejbauer** [comment]
Yuck.

**Comment by SkySkimmer** [comment]
Actually how would it be if we did something like
```
check (Syntax.With (c1,c2)) ((_,t) as t_check) =
  infer c1 >>= as_handler >>= fun h ->
  Value.handle_result h (check c2 t_check >>= fun (ctx,e) ->
                         Value.return_term (Jdg.mk_term ctx e t)) >>= fun v ->
  check_default v t_check
```
It says that if we get `with h handle c` in checking mode for type `T` we should evaluate `c` in checking mode for type `T`, then handle, then check that the handling gave use something of type `T`

**Comment by andrejbauer** [comment]
That assumes that the user will only write non-fancy handlers. I'd very much like to have a solution, but it should be princpled. We're trying to get the checking mode to pass through installation of local hints, that's all. There could be other solutions.

**Comment by SkySkimmer** [comment]
We already make the user write non fancy handlers (top handlers).

**Comment by andrejbauer** [comment]
While this might be nice, it is largely rendered irrelevant by #267 which allows the checking mode to pass through installation of local hints (because local hints are now installed using `now` instead of a handler).
