### ISSUE TITLE
Operations in top handlers

### ISSUE THREAD

**Issue by SkySkimmer** [Andromedans/andromeda#259]
If we have 
```
operation op 0
handle op => None
handle op => op end
do op
```

Should we loop (which we do currently) or should we produce `None` or should we get an unhandled operation `op`?

**Comment by andrejbauer** [comment]
Assuming there is a missing `end` after `None`, we should loop since we decided that top-level handlers were recursive, and the second `handle op` shadows the first one.

**Comment by andrejbauer** [comment]
Closing since there is no clear solution to this. We're likely going to redo top-level handlers anyway.
