### ISSUE TITLE
Names and abstraction of types.

### ISSUE THREAD

**Issue by andrejbauer** [Andromedans/andromeda#270]
There are two kinds of de Bruijn indices, semantically speaking: those of AML (in `Syntax`) and those of the type theory (in `Tt`). It would be good to have a single definition for each, and *not* expose the fact that they are integers (too much).

And while doing it, we can have a look at other types that are lying around to see what can be made abstract.

**Comment by SkySkimmer** [comment]
It seems that only Simplify uses the fact that `Tt.bound = int` (to pass `0 : Tt.bound` to `Tt.occurs`).
So `Tt.bound` could become abstract fairly easily.

**Comment by SkySkimmer** [comment]
Done in 46cebdcb.
