### ISSUE TITLE
Quit and meta level checking

### ISSUE THREAD

**Issue by SkySkimmer** [Andromedans/andromeda#290]
Should
```
#quit
do fun x => x x
```
and
```
#quit
do fun x => x y
```
(`y` not bound anywhere)
evaluate or make an error?

**Comment by andrejbauer** [comment]
Good question. I am in favor of simply eliminating all `#blabla` directives, except possibly `#include`. Another option is that `#blabla` directives always need to happen at desugar pass, whatever they are. If there's suppose to happen in a later pass then they shouldn't be called `#blabla`. In which case `#quit` should really be called `exit ()` or some such (or we can have an `external "exit"`). We could have `#eof` which directs desugar phase (or even the parser) to stop looking, but I see little point in that.

So how about:

1. Eliminate `#quit` and replace it with `external "exit"`.
2. Anything that is `#blabla` is meant to happen during desugaring.
