### ISSUE TITLE
Pattern matching variables in binders

### ISSUE THREAD

**Issue by haselwarter** [Andromedans/andromeda#318]
We currently allow names `x`, `a_name` and pattern variables `?x` `?good_morning` when we pattern match the abstraction part of λ or Π.

Pattern variables are binding and unsurprising to me (yay!).

I find the treatment of names surprising though. As far as I can tell, they're treated like anonymous patterns. I would expect either of these:
* if a variable with the same name is in scope, it has to be an atom and they have to be equal
* an error

wdyt?

```
constant y z : Type

do match λ x : Type, x with
   | ⊢ λ (y : _), _ ⇒ z
   end

do match λ x : Type, x with
   | ⊢ λ (w : Type), _ ⇒ z
   end

fail match λ x : Type, x with
   | ⊢ λ (w : Type), _ ⇒ w
   end
```

**Comment by SkySkimmer** [comment]
>if a variable with the same name is in scope, it has to be an atom and they have to be equal

I don't understand what you mean by that.

Simple names in patterns are there so we can do
```
# constant A : Type
Constant A is declared.
# constant a : A
Constant a is declared.
# do match lambda x : A, x with |- lambda (y : _), y => () end
()
# do match lambda x : A, a with |- lambda (y : _), y => () end
File "?", line 2, characters 4-60: no match found for
⊢ λ (_ : A), a : A → A
```
without `y` being a pattern variable.

**Comment by andrejbauer** [comment]
Is this issue still relevant?
