### ISSUE TITLE
Generalization and unsolved constraints

### ISSUE THREAD

**Issue by SkySkimmer** [Andromedans/andromeda#319]
Consider the list_fold function:

```
let rec fold f acc lst = match lst with
  | [] => acc
  | ?x :: ?tl => fold f (f acc x) tl
  end
```

Its type is intended to be `forall a b, (a -> b -> a) -> a -> list b -> a` but since there are remaining constraints we get ungeneralized `α → β → (list γ) → β`. Constraints are something like
App (α, β, e) and App (e, γ, β) for some e the type of `f acc`.

What is the best way to solve this problem? We could guess unsolved constraints when we get a let but that seems quite aggressive.

Could type schemas hold application constraints? Then the type of fold would be
`forall a b g e [App (a, b, e) & App (e, g, b)], a -> b -> list g -> b`
and when we encounter fold we make fresh app constraints accordingly.

**Comment by andrejbauer** [comment]
There are many things one can do to parametric polymorphism, but I would suggest that we start by not making things extremely complicated. By having typing annotations we will be able to do most things, right? And we have to chose good defaults. Your example seems to show that we should insist that all constraints be resolved at the top level, either by a default guess or by the user providing more information.

**Comment by matijapretnar** [comment]
It's not just the toplevel. If you have

    let rec fold ... = ... in c

you also need to resolve the constraints before inferring `c` in order to keep let-polymorphism.

**Comment by andrejbauer** [comment]
Yeah, do we do that? It would be goot to have a counter-example of that sort that we can then put in the tests.

**Comment by matijapretnar** [comment]
Do we do what? Have let-polymorphism for local lets? That is the expected behavior. I can't think of a concrete example off the top of my head, but I'm sure there's a couple of them floating around in Eff or Andromeda source if one looks. Or, as you suggest, we can try with having local lets monomorphic and resolve constraints only for top-level lets.

**Comment by andrejbauer** [comment]
We don't have application constrainst anymore.
