### ISSUE TITLE
Broken Makefile

### ISSUE THREAD

**Issue by andrejbauer** [Andromedans/andromeda#329]
The `Makefile` is broken (at least) because it does not properly quote interpolation of variables. For instance, we read

```
rm -rf $(LIB_DIR)/*
```

If `LIB_DIR` equals `/usr/evil /home/pretnar` that will not end well.

We should move over to `autoconf`. It's annoying as hell but at least it protects us from such things.

**Comment by matijapretnar** [comment]
What if we use [OASIS](http://oasis.forge.ocamlcore.org/index.html) instead of `autoconf`? It seems to work well for Eff.

**Comment by andrejbauer** [comment]
Does OASIS create self-sufficient standard Unix shell files?

**Comment by matijapretnar** [comment]
It comes with a file `setup.ml`, which is a self-contained OCaml script that does all the work (build, install, uninstall, …), and then it generates `Makefile` and `configure` that more or less call the aforementioned script. So, OCaml is a necessity, but I guess we can assume that, right?

**Comment by andrejbauer** [comment]
I wouldn't trust the OASIS authors that they create compatible shell scripts.

**Comment by matijapretnar** [comment]
If you look at https://opam.ocaml.org/packages/index-popularity.html, you can see that about half of the most popular OPAM packages use OASIS. Any particular reason you wouldn't trust them?

**Comment by andrejbauer** [comment]
Well, if you read [autoconf documentation](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Introduction.html#Introduction) it tells you that making compatible shell scripts and proper configuration is essentially black magic. It is also far far more common than OASIS, and it's what sys admins expect. If you imagine that we might want an installation mechanism that does nto depend on Opam (say, a Debian package) then whoever maintains that will probably prefer autoconf.

**Comment by andrejbauer** [comment]
In the meanwhile, `dune` has become a standard way of packaing OCaml projects, so let's aim to use it.
