### ISSUE TITLE
Checking mode is overly demanding

### ISSUE THREAD

**Issue by christopherastone** [Andromedans/andromeda#347]
When the type checker is in checking mode and sees a syntactic form (lambda, refl, etc.) that it treats specially, it immediately confirms that the type we are checking against has the right form (a product if we are checking a lambda, an equality type if we are checking a refl, etc.).

If not (as in the second 'do' below) type checking fails, without considering alternatives such as coercions. 

Even when the type we are checking against _has_ the right structure, we probably want to consider the same alternatives as inference (instead of immediately failing) if the special-case typing rule doesn't succeed, as in the third example below.

```
constant T : Type
constant c : T

constant CisC : Type
constant coe: (c ≡ c) → CisC

constant reflc : c ≡ c
do
  handle
    reflc : CisC     (* Checking mode just calls inference mode, which succeeds *)
  with
    | coerce (⊢ ?e : c ≡ c) (⊢ CisC) => yield (Coercible (coe e))
  end

fail
  handle
    refl c : CisC    (* Special case for checking mode [wrongly] fails because CisC is not an equality type *)
  with
    | coerce (⊢ ?e : c ≡ c) (⊢ CisC) => yield (Coercible (coe e))
  end

constant p, q : T
constant pq : p ≡ q
fail
  handle
    refl c : p ≡ q   (* Special case for checking mode [wrongly] fails because c != p *)
  with
    | coerce (⊢ ?e : c ≡ c) (⊢ p ≡ q) => yield (Coercible pq)
  end
```

**Comment by andrejbauer** [comment]
When faced with `refl e : A` there are two things we could do:

1. We can try to convert `A` to an equality type, or
2. We can try to coerce `refl e` to `A`.

Currently we do the first option:

    constant xi : CisC ≡ (c ≡ c)
    do
      handle
        refl c : CisC    (* Special case for checking mode [wrongly] fails because CisC is not an equality type *)
      with
        | as_eq (⊢ CisC) => yield (Some xi)
      end

I agree that there is a certain lack of orthogonality going on here.

We originally wanted type ascriptions `e : A` in order to be able to propagate information inward into `e`. If I understand you correctly, you would prefer it to be about coercions instead. Can we balance both?

**Comment by SkySkimmer** [comment]
Checking mode is pretty ad-hoc. It does implicit type annotations on lambdas, automatically uses eq-congr for refl, and the operation checking mode thing. Other than that I wouldn't know how to explain it, so it's hard to tell what it should do.

**Comment by christopherastone** [comment]
The ability to have unannotated lambda parameters is particularly nice, and if we want to use these inside other terms, an obvious goal is to "push down" type information as much as possible, in order to reach unannotated lambdas. (I have less intuition how useful automatic eq-congr is in practice.)

In the presence of coercions and "weird" type equalities (as in my original example), we know that pushing types into subterms might not type check, even though naive "infer" mode would succeed. So instead of failing immediately as soon as the checking-mode code fails, we should probably backtrack and try infer mode before giving up.

(Possibly we could try infer mode immediately if the term doesn't contain any unannotated-lambdas or other subterms that would benefit from checking mode, and avoid the backtracking.)

Of course, if *both* checking mode and infer mode fail when evaluating a term, they'll produce different error messages. So then, which error do we report?

**Comment by andrejbauer** [comment]
This seems to have been resolved in favor of switching to infer more.

```
rule Id (A type) (a : A) (b : A) type ;;
rule refl (A type) (a : A) : Id A a a ;;

rule T type ;;
rule c : T ;;
rule CisC type ;;
rule coe (p : Id T c c) : CisC ;;

handle
  refl T c : CisC
with
  ML.coerce q _ -> yield (ML.Some (coe q))
end
;;
```

This produces:
```
Rule Id is postulated.
Rule refl is postulated.
Rule T is postulated.
Rule c is postulated.
Rule CisC is postulated.
Rule coe is postulated.
- : judgement = ⊢ coe (refl T c)
```
