### ISSUE TITLE
Examples directory is hard to keep up-to-date

### ISSUE THREAD

**Issue by christopherastone** [Andromedans/andromeda#350]
Ideally, all the examples would work in the current version of Andromeda, and we would have an easy way to know when they break (as we do with the script in the tests directory).

**Comment by andrejbauer** [comment]
I suppose we should just incorporate the examples into `make tests` but keep them in the `examples` directory?

**Comment by andrejbauer** [comment]
We're currently short of good examples in Andromeda 2, there is MLTT put there by @haselwarter and @anjapetkovic? Anyhow, I am closing this, we'll just have to keep examples up to date.
