### ISSUE TITLE
Evidence that substitition preserves equality

### ISSUE THREAD

**Issue by andrejbauer** [Andromedans/andromeda#359]
In the equality checking algorithm, where we perform a beta step, we seemingly need evidence that substitution preserves equality in _both_ arguments:

> if `y : A |- b1 == b2 : B` and `a1 == a2 : A` then `b1[a1/y] == b2[a2/y] : B[a1/y]`

We can do half of this now. If `y : A |- p : b1 == b2 : B` then `p where y = a1` would give evidence of `b1[a1/y] == b2[a1/y] : B[a1/y]`. But how do we vary `a1`?

**Comment by SkySkimmer** [comment]
If we have `|- b[a1/y] == b[a2/y] : B[a1/y]` when `y : A |- b : B` and `|- a1 == a2 : A` we can do it by transitivity.
And we do have it:
`b[a1/y] == (lambda y, b) a1 : B[a1/y]` by beta_step
`(lambda y, b) a1 == (lambda y, b) a2) : B[a1/y]`by congr_lambda
`(lambda y, b) a2 == b[a2/y] : B[a2/y]`by beta_step
`B[a1/y] == B[a2/y]` by going through `(lambda y, B) ai` (works since `Type` doesn't depend on y).

**Comment by andrejbauer** [comment]
We noticed this but were not sure whether we want to do it this way, or provide a direct `congr_subst`.

**Comment by andrejbauer** [comment]
In Andromeda 2 I am pretty sure we can do this sort of thing using `congruence` and `convert`:
```
rule A type ;;
rule B (a : A) type ;;
rule b₁ (a : A) : B a ;;
rule b₂ (a : A) : B a ;;
rule ξ (a : A) : b₁ a ≡ b₂ a : B a ;;
rule a₁ : A ;;
rule a₂ : A ;;
rule α : a₁ ≡ a₂ : A ;;

rule symmetry
   (X type) (x : X) (y : X)
   (x ≡ y : X as α) :
   y ≡ x : X
;;

rule transitivity
   (X type) (x : X) (y : X) (z : X)
   (x ≡ y : X as α) (y ≡ z : X as β) :
   x ≡ z : X
;;

let p = ξ a₁ ;;
let q = congruence b₂ (b₂ a₁) (b₂ a₂) α ;;
let r = congruence B (B a₂) (B a₁) (symmetry A a₁ a₂ α) ;;
let s = transitivity (B a₁) (b₁ a₁) (b₂ a₁) (convert (b₂ a₂) r) p q ;;
```
Output:
```Rule A is postulated.
Rule B is postulated.
Rule b₁ is postulated.
Rule b₂ is postulated.
Rule ξ is postulated.
Rule a₁ is postulated.
Rule a₂ is postulated.
Rule α is postulated.
Rule symmetry is postulated.
Rule transitivity is postulated.
val p :> judgement = ⊢ b₁ a₁ ≡ b₂ a₁ : B a₁
val q :> judgement = ⊢ b₂ a₁ ≡ b₂ a₂ : B a₁
val r :> judgement = ⊢ B a₂ ≡ B a₁
val s :> judgement = ⊢ b₁ a₁ ≡ b₂ a₂ : B a₁
```

It may not be pretty, but I think it's principled. One possible improvement is to try to do the same as a derived rule, in which case `B` will be a meta-variable, so we will need a way of deriving equalities involving instantiations of meta-variables. To be more precise, we would like to have something like this, where `magic` is just a placeholder. This gives us an error because Andromeda cannot tell that in the defintion of `q` the term `b₂{a₂}` has type `B{a₁}`. We need some sort of a meta-theorem that gives us congruence for meta-variables, more or less.

```
rule symmetry
   (X type) (x : X) (y : X)
   (x ≡ y : X as α) :
   y ≡ x : X
;;

rule transitivity
   (X type) (x : X) (y : X) (z : X)
   (x ≡ y : X as α) (y ≡ z : X as β) :
   x ≡ z : X
;;

operation magic : judgement ;;

derive
  (A type)
  ({a : A} B type)
  ({a : A} b₁ : B{a})
  ({a : A} b₂ : B{a})
  ({a : A} b₁{a} ≡ b₂{a} : B{a} as ξ)
  (a₁ : A)
  (a₂ : A)
  (a₁ ≡ a₂ : A as α)
->
  let p = ξ{a₁} in
  let q = magic :? (b₂{a₁} ≡ b₂{a₂} : B{a₁} as ?) in
  let r = magic :? (B{a₂} ≡ B{a₁} as ?) in
  let s = transitivity B{a₁} b₁{a₁} b₂{a₁} (convert b₂{a₂} r) p q in
  s
```
