### ISSUE TITLE
Check match exhaustivity?

### ISSUE THREAD

**Issue by SkySkimmer** [Andromedans/andromeda#378]
Are there times when it makes sense to detect if and warn when a match is not exhaustive, and if so when is that exactly?

**Comment by andrejbauer** [comment]
I think that always makes sense, but in our case it will be impossible to do whenever we match against `judgment`. We would need a sensible strategy on when to warn the user, or at the very least some sensible switches. Another option is to indicate in `match` somehow that you think you've got an exhaustive check. (Although I have not seen that in any language.)

**Comment by andrejbauer** [comment]
We should either come to some sort of a conclusion, or close the issue. Is there a reasonable strategy that we could employ here? For instance, we could just assume that every match against `judgment` is complete, and have exhaustiveness checking built on top of that.

**Comment by andrejbauer** [comment]
I am closing this issue, if anyone has any ideas on how to reasonably perform exhaustiveness checks, plase tell us.
