### ISSUE TITLE
Website broken?

### ISSUE THREAD

**Issue by jaens** [Andromedans/andromeda#383]
The link in `README.md` eventually redirects to http://www.andromeda-prover.org/ which fails to load due to a DNS error.

**Comment by SkySkimmer** [comment]
We've already seen this in #382.

**Comment by jaens** [comment]
Same result from machines on two different networks:
```
> dig www.andromeda-prover.org

; <<>> DiG 9.10.3-P4-Debian <<>> www.andromeda-prover.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51739
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.andromeda-prover.org.      IN      A

;; AUTHORITY SECTION:
andromeda-prover.org.   1800    IN      SOA     dns1.siel.si. dns.siel.si. 3 28800 7200 604800 86400

;; Query time: 19 msec
;; SERVER: 10.1.31.38#53(10.1.31.38)
;; WHEN: Wed Apr 12 01:26:36 UTC 2017
;; MSG SIZE  rcvd: 105
```

**Comment by andrejbauer** [comment]
I wonder whether these are intermitent problems, or someting permanent. I can't reproduce the problem on my side, but that might be because I've got the DNS record cached. (How do I clear the DNS cache on OSX?)

**Comment by jaens** [comment]
Loads for me now, which I guess makes it worse, since it could be intermittent...
