### ISSUE TITLE
Simultaneous substitution

### ISSUE THREAD

**Issue by mikeshulman** [Andromedans/andromeda#387]
How do I substitute for multiple assumptions at the same time?  I've tried variations on the syntax described at <http://www.andromeda-prover.org/meta-language.html#substitution>, like `c1 where x = c2 where y = c3` or `c1 where x = c2 and y = c3` or `c1 where (x,y) = (c2,c3)`, but haven't found anything that works.  And I don't immediately see any way to work around the absence of such a syntax, for instance if `y` has a type that depends on `x`, I can't substitute for one of them first and then the other because the intermediate result would be ill-typed, no matter which order I do it in (this seems to be in fact what `c1 where x = c2 where y = c3` tries to do).

**Comment by mikeshulman** [comment]
Hmm, actually maybe that isn't what `c1 where x = c2 where y = c3` tries to do.  I'm not sure what it's trying to do, maybe `c1 where x = (c2 where y = c3)`?  Anyway it doesn't work.

**Comment by haselwarter** [comment]
Hi @mikeshulman, what would be a concrete example where you can't decompose a substitution to go in two steps?

**Comment by mikeshulman** [comment]
Ah, I think maybe in trying to construct such an example I found the correct syntax: `(c1 where x = c2) where y = c3`.  I was thinking that that wouldn't work because after substituting `c2` for `x` the type of `y` has to change in order that `c3` would be substitutable for it, but apparently Andromeda does handle that correctly as long as the substitutions are appropriately bracketed.

I assume that the reason `c1 where x = c2 where y = c3` doesn't work is that Andromeda is actually parsing it as `c1 where x = (c2 where y = c3)`.  Is that really the intended behavior?  It seems more intuitive for me for substitutions to associate to the left, which I think is why I didn't think of trying to add parentheses explicitly at first.
