### ISSUE TITLE
Add build instructions to the README

### ISSUE THREAD

**Issue by meteficha** [Andromedans/andromeda#461]
I'm unfamiliar with OCaml, so for me it's a bit hard to blindly build Andromeda.  What I did on MacOS was:

1. `brew install ocaml ocamlbuild opam`
2. `opam install .` inside the Andromeda repo.

**Comment by haselwarter** [comment]
There are now updated instructions at http://www.andromeda-prover.org/install.html
Do these instructions work for you?

**Comment by meteficha** [comment]
Perfect!  Please link it from the README too in case someone stumbles to the repo first.

Cheers!
