### ISSUE TITLE
Congruence errors

### ISSUE THREAD

**Issue by mikeshulman** [Andromedans/andromeda#472]
I think either I don't understand how `congruence` is supposed to work, or it isn't working the way it's supposed to.  If the former, can someone explain how it is supposed to work?

```
rule eq_term_refl (A type) (a : A) : a ≡ a : A

rule eq_type_refl (A type) : A ≡ A

rule Π (A type) ({x : A} B type) type

rule λ (A type) ({x : A} B type) ({x : A} f : B{x}) : Π A B

rule app (A type) ({x : A} B type) (s : Π A B) (a : A) : B{a}

rule A type
rule a : A
rule B (x : A) type
rule f (x : A) : B x
rule g : Π A ({x:A} B x) ;;

congruence (Π A ({x:A} B x))
           (Π A ({x:A} B x))
           (eq_type_refl A)
           ({x : A} eq_type_refl (B x)) ;;
(* - : judgement = ⊢ Π A ({x} B x) ≡ Π A ({x} B x) *)

congruence (app A ({x:A} B x) g a) (app A ({x:A} B x) g a)
           (eq_type_refl A) ({x:A} eq_type_refl (B x))
           (eq_term_refl (Π A ({x:A} B x)) g) (eq_term_refl A a) ;;
(* Nucleus error: term expected *)

congruence (λ A ({x:A} B x) ({x:A} f x))
           (λ A ({x:A} B x) ({x:A} f x))
           (eq_type_refl A)
           ({x : A} eq_type_refl (B x))
           ({x : A} eq_term_refl (B x) (f x)) ;;
(* Nucleus error: too few arguments *)
```

**Comment by andrejbauer** [comment]
You're very brave to use the unfinished version that's at the head of `master` right now :-)

`congruence e e' ...` works when `e` and `e'` are both applications of the same constructor `C`. In `...` you need to provide as many additional arguments as there are arguments to `C`.

As far as I can tell you uncovered a bug, probably in the meta-language. I can't investigate right now, but will do so as soon as I can.

**Comment by mikeshulman** [comment]
Well, I just thought I would try messing around a bit out of curiosity, and it seems to work pretty well for an unfinished version.  I'm looking forward to its being finished.
