### ISSUE TITLE
The dynamically-variadic nature of "congruence"

### ISSUE THREAD

**Issue by mikeshulman** [Andromedans/andromeda#486]
This is weird:

```
let mycong B ξ =
  match ξ with
  | a ≡ b : A -> congruence B{a} B{b} ξ
  end

rule A type
rule B (x : A) type
rule C (x : A) (y : A) type
rule a : A
rule b : A
rule ξ : a ≡ b : A ;;

mycong ({x:A} B x) ξ ;; (* works *)

mycong ({x:A} A) ξ ;; (* too many arguments *)

mycong ({x:A} C x a) ξ ;; (* too few arguments *)
```

I think I understand why this is happening, but it seems to make `congruence` less useful than it might be.  Is there a better way to implement something like `mycong`?  The only thing I can think of is to postulate, or derive, a separate rule for "1-parameter congruence", but then of course one would also need one for "2-parameter congruence" etc.

**Comment by andrejbauer** [comment]
Yes, you can use derived rules. These are like rules, but you derive them from existing rules. They take the form `derive P1 ... P2 -> C` where `Pi` are premisess (written as in a rule) and `C` is a computation that computes a judgement (from the premises), the conclusion.

```
let mycong =
  derive (A type) ({x : A} B type) (a : A) (b : A) (a ≡ b : A as ξ) ->
    congruence B{a} B{b} ξ
;;

rule A type
rule B (x : A) type
rule C (x : A) (y : A) type
rule a : A
rule b : A
rule ξ : a ≡ b : A ;;

mycong A ({x:A} B x) a b ξ ;;

mycong A ({x:A} A) a b ξ ;;

mycong A ({x:A} C x a) a b ξ ;;
```

**Comment by mikeshulman** [comment]
Sorry, I think my example was too simple to get the point across.  I had figured out how to write derived rules by reading `tests/nucleus/derive.m31`.  Right now the AML function I'm trying to write cannot itself be replaced by a derived rule, but somewhere inside of it I need to apply a congruence rule where the "head" is an abstracted metavariable supplied by the user, and I was surprised to discover that using `congruence` was unstable because the form of what the user supplied would change the number of arguments required by `congruence`.  But based on your answer I guess that the solution I had thought of is the intended one, so I'll go that way.
