### ISSUE TITLE
Matching against a neutral application

### ISSUE THREAD

**Issue by mikeshulman** [Andromedans/andromeda#487]
Is there a way to match against a "neutral" application of a metavariable?  Something like

```
match T with
| B{x:A} type -> (* do something with x:A and B {x:A} type *)
end
```

**Comment by mikeshulman** [comment]
It would also be nice to be able to match against "some rule application" without knowing what the rule is.

Context: I'm playing around with writing my own equality-checking handler.  Nothing so fancy/extensible as the intended built-in one, but I'm hoping that I can implement beta- and eta-rules for a small finite list of type constructors (like core MLTT) using a standard algorithm.  But unless I can match against applications of unknown metavariables and rules so as to apply congruences on their arguments, it seems that my handler won't work in derived rules or in the context of additional primitive rules.

**Comment by andrejbauer** [comment]
We have all of these planned. The idea is that matching should allow one to completely reify the syntax. Please hold your breadth.

**Comment by andrejbauer** [comment]
Also, don't waste your time implementing equality checking, we're doing it actively in OCaml (but outside of nucleus) for speed and easy of use.

**Comment by mikeshulman** [comment]
Sorry; I'll try to stop bothering you all.

I know you're doing it in OCaml; I wanted to do it myself as an educational exercise.  I wouldn't count that as a waste even if your implementation were already available.  It should be possible, shouldn't it?
