### ISSUE TITLE
Separate the type of terms with de Bruijn indices from those that do not

### ISSUE THREAD

**Issue by andrejbauer** [Andromedans/andromeda#50]
Just like we have a separation between `Tt.term` and `Tt.ty` we should have a separation between terms that may contain de Bruijn indices (bare bound variables) and those that do not. This is likely going to prevent the sort of headaches we experience now when we forget to use `Tt.abstract` or `Tt.unabstract`.

**Comment by SkySkimmer** [comment]
Terms are now usually wrapped inside a Jdg type so this doesn't really come up anymore.
