### ISSUE TITLE
Pick a name for the programming language

### ISSUE THREAD

**Issue by andrejbauer** [Andromedans/andromeda#52]
We need a name for the programming language that the kernel evaluates. Maybe something related to travelling to the Andromeda galaxy, or something from Greek mythology?

**Comment by pthariensflame** [comment]
How about "Messier"?

**Comment by andrejbauer** [comment]
My immediate reaction is "too French" but other than that it's nice.

**Comment by markokoleznik** [comment]
how about Strain, after the classic http://www.imdb.com/title/tt0066769/? :D

**Comment by andrejbauer** [comment]
Yikes.. How about simply M31?

**Comment by andrejbauer** [comment]
Actually, from a user perspective it is better not to distinguish between the programmign language and the type theory, as the input to Andromeda *is* the program. So, let's just call it *Andromeda*.
