### ISSUE TITLE
Add useful data structures

### ISSUE THREAD

**Issue by andrejbauer** [Andromedans/andromeda#55]
The programming language has no data structures, which makes it hard to program any sort of interesting algorithm. I am hesitant to have a large-scale language on top of type theory (i.e., a whole new level of simple types), but maybe that is what we need. We could first experiment with an untyped language that has good support for the common structures (lists, dictionaries).

**Comment by andrejbauer** [comment]
We now have lists  (f5cf72bd7c039a6c279801113e52058cb419879b ) and tuples (33773caac260dbf4c1f51890f36246088dfd89af). It would be useful to have maps, I think, but I am closing this as it is very non-specific.

**Comment by andrejbauer** [comment]
Actually, which primitive data structures would be useful to have? Probably dictionaries/maps. What about sets?

**Comment by pthariensflame** [comment]
Sets are almost trivially recoverable as a special case of dictionaries where the value is the unit type, so I don't think having both at once is necessary.

**Comment by andrejbauer** [comment]
We have ML type definitions now. If we need native dictionaries or some such, we'll do them later.
