### ISSUE TITLE
Allow empty signatures and structures

### ISSUE THREAD

**Issue by andrejbauer** [Andromedans/andromeda#74]
Caveat: is `{}` an empty signature or an empty structure?

However, from a mathematical point of view it is silly not to have these. (We get the unit type for free)

**Comment by pthariensflame** [comment]
![Why not both?](http://www.reactiongifs.us/wp-content/uploads/2014/05/why_not_both.gif)

**Comment by andrejbauer** [comment]
How about `{}` for the empty record and `unit` for the empty signature?

**Comment by haselwarter** [comment]
I'd rather not make `unit` a reserved keyword :/ I'm also not so sure about fixing "the" unit type.
We could use `{| ... |}` for structures and `{ ... }` for signatures. More principled, but also kind of annoying. Here are some ideas:
```
() : {}
{} : {:}
{} : ⊤
〈〉 : 1
tt : unit
```

**Comment by andrejbauer** [comment]
We could say that `{}` is a structure except in checking mode where `{} :: Type` is a the signature. Then whenever `{}` is used in checking mode and we're expecting a `Type` it would "just work". Would it?

@SkySkimmer (who's sitting next to me) says "people will just define `unit` or something to be the same thing as `{} :: Type`. I would.

**Comment by andrejbauer** [comment]
If we make `(a, b, c)` to be an abbreviation for `{1 := a, 2 := b, 3 := c}` then `()` would naturally be the empty structure. The empty singature is then `{}`.  So I like

     () : {}
