### ISSUE TITLE
Implement resources

### ISSUE THREAD

**Issue by andrejbauer** [Andromedans/andromeda#85]
It would be nice to have resources in the sense of http://arxiv.org/abs/1203.1539 which are implemented in Eff. This would give us a humane way of working with state.

**Comment by andrejbauer** [comment]
I wonder how useful recourses without instances are. For example, references and self-modifying data structures (e.g. balanced trees) are nicely implemented with recources. But without instances only one copy of a references or a self-modifying data structure would exist.

**Comment by andrejbauer** [comment]
Closed by #86, more or less. We still need to do something about state.

**Comment by SkySkimmer** [comment]
More like closed in #90.
