### ISSUE TITLE
Top level handlers

### ISSUE THREAD

**Issue by SkySkimmer** [Andromedans/andromeda#86]
In my branch at commit 17ccb36 (yet to be pull-request) if the kernel cannot check an equality `u=v` it emits an operation `#equal ('pair u v)`. The value given to the continuation should be:
- `'some eq` where `eq : u == v` if user heuristics succeed in solving the equation
- `'none` otherwise

The error when `'none` is returned is nicer than the uncaught operation error.
It would be nice to be able to say

    Handle | #equal _ k => k 'none end.
in the prelude instead of having to wrap that handler around every computation in order to get those nicer errors.

**Comment by andrejbauer** [comment]
See issue #85, what you are proposing is a special case of a resource. In this case `#equal` would have an associated resource that always passes `'none`.
