### ISSUE TITLE
Getting rid of the expressions/computation distinction

### ISSUE THREAD

**Issue by andrejbauer** [Andromedans/andromeda#88]
I would like to hear at least @matijapretnar's opinion, but also others.

In Eff there is a distinction between expessions and computations. There it makes a lot of sense to have it, for operational and semantics reasons.

However, in Andromeda we departed from the distinction. For instance, a spine is of the form `e c1 ... cn` where `e` is an expressions and `ci` are computations (this is so because we want do be in checking mode when we evaluate `ci`).

@SkySkimmer suggested that perhaps we could just get rid of the distinction. This would basically amount to making everything a computation. We would need to prescribe order of evaluation in applications, which we already do.

Does anyone seen an obstacle? If not, we should probably do it as it would simplify the language, and desugaring as well.

**Comment by matijapretnar** [comment]
I guess it makes sense. The operational semantics and effect (but not type) system might get a bit messier, but not too much. Do you even plan to have a type system?

**Comment by andrejbauer** [comment]
I think we do. Can you imagine writing thousands of code without types?

**Comment by SkySkimmer** [comment]
In #55 we say we're not sure.

**Comment by andrejbauer** [comment]
It seems like we're more sure nowadays :-)
