### ISSUE TITLE
`Optimise Tt.term` command

### ISSUE THREAD

**Issue by haselwarter** [Andromedans/andromeda#93]
I think it will be handy to have a command which optimises a Tt.term (e.g. flattening spines).

Then we will be able to do things like `snf` outside the kernel, avoiding some problems like #92

In fact, @SkySkimmer remarked that `snf` can easily be implemented as follows:

```
Let rec snf' t :=
  let t := whnf t in
  match t with
  | [e1 e2] |- e1 e2 => (snf' e1) (snf' e2)
  | _ => t
  end.
```

But this messes with spine nesting and sharing. I'd still rather have this in the prelude and wrap it with a call to `optimise` when we encounter performance problems.

**Comment by andrejbauer** [comment]
You cannot flatten spines without comparing the typing annotations, and we do not want `Tt` to depend on `Equal`. So at best we could flatten spines when the typing annotations agree modulo alpha equality, but we should investigate how helpful that would be.
