### ISSUE TITLE
Do not always use [simplify] in toplevel checks

### ISSUE THREAD

**Issue by haselwarter** [Andromedans/andromeda#94]
If we always run `simplify` in TopCheck it can be hard to see the shape of a term, which is useful, e.g. when we write normalisation functions. It could become an operation or a built-in, but then we always have to specify it and I suspect most of the time we'll still want it.

An alternative would be to add a Print command that displays a judgement without simplification.

NB: we can avoid simplification by using tags, as currently TopCheck does not simplify tags. Which, maybe it should, sometimes.

**Comment by andrejbauer** [comment]
In fact I think we now do have a `print` command, see #91.

**Comment by SkySkimmer** [comment]
Indeed.
